import { createContext, useContext, useState, useEffect, useCallback } from 'react';
import { api } from '../api';
import { useAuth } from './AuthContext';

const AppContext = createContext(null);

const DEFAULT_PROFILE = {
  address: null, staffSize: null, category: null, subcategory: null,
  businessType: null, registrationType: null, gstin: null, email: null,
  mobile: '+918569852254',
};

const TEAM_MEMBERS = [
  {
    id: 'member_001', name: 'gurvinder singh', isYou: true,
    employeeId: null, email: null, mobile: '+91 85698 52254',
    role: 'Primary Admin', reportsTo: null, walletStatus: 'Not Issued',
    inviteStatus: 'Accepted',
  },
  {
    id: 'member_002', name: 'suraj', isYou: false,
    employeeId: null, email: null, mobile: '+91 88949 72942',
    role: 'Employee', reportsTo: null, walletStatus: 'Not Issued',
    inviteStatus: 'Accepted',
  },
];

const WHATS_NEW = [
  {
    version: 'v4.3.0', date: 'Apr 1, 2026', category: 'Payments',
    items: [
      { title: 'Download Expense Reports with Permanent Attachments', description: 'Expense reports now download as a ZIP file with all receipt images included.', link: 'Download a report' },
      { title: 'All Reports', description: 'Access reports generated by all employees from a single section.', link: 'View Reports' },
    ],
  },
];

export function AppProvider({ children }) {
  const [businesses, setBusinesses] = useState([]);
  const [currentBusinessId, setCurrentBusinessId] = useState(null);
  const [cashbooks, setCashbooks] = useState([]);
  const [loadingBiz, setLoadingBiz] = useState(true);
  const [loadingBooks, setLoadingBooks] = useState(false);
  const [profiles, setProfiles] = useState({});

  const currentBusiness = businesses.find((b) => b.id === currentBusinessId) || null;

  // ── Load businesses on mount ────────────────────────────
  useEffect(() => {
    setLoadingBiz(true);
    api.businesses.list()
      .then(({ businesses: list }) => {
        setBusinesses(list);
        if (list.length > 0) {
          setCurrentBusinessId((prev) => prev && list.find((b) => b.id === prev) ? prev : list[0].id);
        }
      })
      .catch((err) => console.error('[AppContext] businesses load failed:', err.message))
      .finally(() => setLoadingBiz(false));
  }, []);

  // normalise DB snake_case → camelCase for cashbook rows
  function normBook(b) {
    return {
      ...b,
      businessId: b.business_id,
      createdAt: b.created_at,
      transactionCount: parseInt(b.transaction_count || 0, 10),
    };
  }

  // ── Load cashbooks when business changes ────────────────
  useEffect(() => {
    if (!currentBusinessId) { setCashbooks([]); return; }
    setLoadingBooks(true);
    api.cashbooks.list(currentBusinessId)
      .then(({ cashbooks: list }) => setCashbooks(list.map(normBook)))
      .catch((err) => console.error('[AppContext] cashbooks load failed:', err.message))
      .finally(() => setLoadingBooks(false));
  }, [currentBusinessId]);

  // ── Business CRUD ───────────────────────────────────────
  const addBusiness = useCallback(async ({ name, category, businessType }) => {
    const { business } = await api.businesses.create({ name, category, businessType });
    setBusinesses((prev) => [...prev, business]);
    setCurrentBusinessId(business.id);
    return business.id;
  }, []);

  // ── Cashbook CRUD ───────────────────────────────────────
  const addCashbook = useCallback(async (name) => {
    const { cashbook } = await api.cashbooks.create(currentBusinessId, { name });
    setCashbooks((prev) => [...prev, normBook(cashbook)]);
    return cashbook.id;
  }, [currentBusinessId]);

  const renameCashbook = useCallback(async (bookId, name) => {
    await api.cashbooks.rename(currentBusinessId, bookId, name);
    setCashbooks((prev) => prev.map((b) => b.id === bookId ? { ...b, name } : b));
  }, [currentBusinessId]);

  const deleteCashbook = useCallback(async (bookId) => {
    await api.cashbooks.delete(currentBusinessId, bookId);
    setCashbooks((prev) => prev.filter((b) => b.id !== bookId));
  }, [currentBusinessId]);

  // ── Profile (kept local for now) ───────────────────────
  const currentProfile = profiles[currentBusinessId] || { ...DEFAULT_PROFILE };
  const filledFields = Object.values(currentProfile).filter((v) => v !== null && v !== '').length;
  const totalFields = Object.keys(currentProfile).length;
  const profileStrength = Math.round((filledFields / totalFields) * 100);

  const updateProfile = (fields) => {
    setProfiles((prev) => ({
      ...prev,
      [currentBusinessId]: { ...prev[currentBusinessId], ...fields },
    }));
  };

  const { user: authUser } = useAuth();
  const userName = authUser?.name || authUser?.email?.split('@')[0] || 'User';
  const user = {
    name: userName,
    mobile: authUser?.mobile || '',
    email: authUser?.email || '',
    initials: userName.charAt(0).toUpperCase(),
  };

  const currentCashbooks = cashbooks.filter((b) => (b.businessId || b.business_id) === currentBusinessId);

  return (
    <AppContext.Provider value={{
      businesses,
      addBusiness,
      currentBusiness,
      currentBusinessId,
      setCurrentBusinessId,
      cashbooks: currentCashbooks,
      addCashbook,
      renameCashbook,
      deleteCashbook,
      loadingBiz,
      loadingBooks,
      teamMembers: TEAM_MEMBERS,
      currentProfile,
      profileStrength,
      filledFields,
      totalFields,
      updateProfile,
      user,
      whatsNew: WHATS_NEW,
    }}>
      {children}
    </AppContext.Provider>
  );
}

export const useApp = () => useContext(AppContext);
